services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /media/vinay/Study1/IIT/BigData/Project/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /media/vinay/Study1/IIT/BigData/Project/Prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - 'storage.tsdb.path=/media/vinay/Study/IIT/BigData/Project/Prometheus'
      - '--storage.tsdb.retention.time=30d'
    restart: unless-stopped
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:8.5.3-ubuntu
    container_name: grafana
    volumes:
     - /media/vinay/Study1/IIT/BigData/Project/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
     - :/etc/grafana/config.ini
     - /media/vinay/Study/IIT/BigData/Project/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    ports:
      - '3000:3000'